

export const CREATE_GOODS_TO_CART = 'CREATE_GOODS_TO_CART'
export const ADD_GOODS_FROM_CART = 'ADD_GOODS_FROM_CART'
export const CUT_GOOGS_FROM_CART = 'CUT_GOOGS_FROM_CART'
export const DELETE_GOODS_FROM_CART = 'DELETE_GOODS_FROM_CART'
export const GET_GOODS_LIST = 'GET_GOODS_LIST'